version: '3.8'

services:
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    ports:
      - "5435:5432"
    volumes:
      - payment-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  payment-service:
    build: ./payment-service
    ports:
      - "50052:50052"
    depends_on:
      - payment-db
      - rabbitmq
    environment:
      PORT: 50052
      DB_HOST: payment-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: paymentdb

  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - order-db
      - payment-service
    environment:
      REST_PORT: 8080
      PAYMENT_SERVICE_ADDR: payment-service:50052
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: orderdb

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

volumes:
  order-data:
  payment-data: